### ISSUE TITLE
Trailing space in console prevents command from being evaluated

### ISSUE THREAD

**Issue by doublec** [aliceml/aliceml#4]
This is an import of doublec/aliceml#5 from the previous repository.

Entering code without a trailing space after the semicolon works fine in the interactive console when pressing enter:

    1+2;<enter>
    val it : int = 2

Adding a trailing space followed by a newline causes the console to wait for further input. Only another semicolon appears to cause the first line to be processed:

    1+2;<space><enter>
    ;
    val it : int = 2

**Comment by rossberg** [comment]
FWIW, this was intentional. The purpose was to allow entering/pasting multiline sequential statements, and continuing input on the next line after a semicolon, by simply adding a space. Hacky but convenient...

**Comment by doublec** [comment]
Interesting, thanks. I'll close those since it's intentional.
